export const countries = [
    "Lithuania",
    "Poland",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Portugal",
    "Netherlands",
    "Belgium",
    "Sweden",
    "Norway",
    "Finland",
    "Denmark",
    "Latvia",
    "Estonia",
];