import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './styles/normalize.css';
import './styles/globals.css';
import './styles/theme.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const EmptyLayout = ({ children }: LayoutProps<'/'>) => {
  return <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <body>
       {children}
    </body>
  </html>;

};

export default EmptyLayout;
